name: Simple CI Pipeline

on:
  # This allows the workflow to be triggered manually with parameters
  workflow_dispatch:
    inputs:
      PARAM1:
        description: 'Enter the first parameter'
        required: true
      PARAM2:
        description: 'Enter the second parameter'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Use the environment variables (parameters) passed dynamically
      - name: Run Script with Parameters
        env:
          PARAM1: ${{ github.event.inputs.PARAM1 }}
          PARAM2: ${{ github.event.inputs.PARAM2 }}
        run: |
          echo "Parameter 1 value: $PARAM1"
          echo "Parameter 2 value: $PARAM2"
